stages:
  - build

build_job:
  stage: build
  script:
    - |
      REPO2DOCKER_IMAGE=8d490cf
      CI_COMMIT_SHA_SHORT="$(git rev-parse --short HEAD)"
      if git diff HEAD~ --name-only | egrep 'Dockerfile'; then
        echo "####### gesiscss/singleuser-orc:r2d-$CI_COMMIT_SHA_SHORT"

        # install repo2docker
        git clone https://github.com/jupyter/repo2docker.git
        cd repo2docker
        git checkout $REPO2DOCKER_IMAGE
        python3 -m pip install -e .
        cd ..

        # build image and push
        docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
        ~/.local/bin/jupyter-repo2docker --image-name gesiscss/singleuser-orc:r2d-$CI_COMMIT_SHA_SHORT --no-run .
        docker push gesiscss/singleuser-orc:r2d-$CI_COMMIT_SHA_SHORT
      fi;
  only:
    - master
  tags:
    - data_science_image
  when: on_success
  allow_failure: false
  dependencies: []
  retry: 1
